### ISSUE TITLE
Rename `YieldCurve` type to something else

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/Yields.jl#103]
It's really only used in the context of what's now called the bootstrapping class of curves. Maybe new name would be `BootrappedYieldCurve`?

It's not in the [documented API](https://juliaactuary.github.io/Yields.jl/stable/api/), so I don't think this would be considered breaking.

**Comment by PrajwalBorkar** [comment]
> It's really only used in the context of what's now called the bootstrapping class of curves. Maybe new name would be `BootrappedYieldCurve`?
> 
> It's not in the [documented API](https://juliaactuary.github.io/Yields.jl/stable/api/), so I don't think this would be considered breaking.

Renamed variable please review for any changes. :)
