### ISSUE TITLE
`ObservableQuote` Questions

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/Yields.jl#144]
- in the docstring for `BulletBondQuote`, should the `yield` parameter really be called `coupon_rate`? Isn't the yield implied by the coupon frequency, prices, and maturity? 
- Implicitly, are unit payments assumed? E.g. should one interpret the price of `4.5` in the `ZeroCouponQuote` docstring as implying a ZCB with a very negative yield?

@kasperrisager

**Comment by kasperrisager** [comment]
* Yes, `coupon_rate` would be better. Same goes for `SwapQuote`.
* Yes, that's how it's intended
