### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/Yields.jl#145]
Sketching out revisions to API that would be breaking:

### Status Quo

- Currently, there are constructors that dictate how the given `Float64` arguments should be interpreted.
  -  E.g. `Yields.Par` vs Yields.Forward`, etc.:

```julia
riskfree_maturities = [0.5, 1.0, 1.5, 2.0]
riskfree    = [5.0, 5.8, 6.4, 6.8] ./ 100     #spot rates, annual effective if unspecified

rf_curve = Yields.Zero(riskfree,riskfree_maturities)
```

  - `SmithWilson` is the only curve type that uses the `ObservableQuotes`:
``` julia
	SmithWilson(zcq::Vector{ZeroCouponQuote}; ufr, α)
    SmithWilson(swq::Vector{SwapQuote}; ufr, α)
    SmithWilson(bbq::Vector{BulletBondQuote}; ufr, α) 
```

### Idea

New API would be:

```julia
curve(method::CurveMethod,quotes::Observable)::T<:AbstractRateCurve
```

so the example above would instead be something like:

```julia
riskfree_maturities = [0.5, 1.0, 1.5, 2.0]
riskfree    = [5.0, 5.8, 6.4, 6.8] ./ 100     #spot rates, annual effective if unspecified
zr = ZeroRate.(riskfree,riskfree_maturities)

rf_curve = curve(Bootstrap(),zr)
```

To some extent, we should be able to automatically convert data to minimize the methods that need to be specified, e.g. a `ZeroRate`(Quote) implies a `ZeroCouponBond`(Quote) price
### Benefits

I think there are some benefits to this:

- Converge API for `SmithWilson` and all of the other constructor types
- More uniform API able to handle different types of "quotes", whether that's yields or prices.
- More extensible for users to define custom curve constructors. Just need to extend the `curve` method for their new `CurveMethod` which can dispatch based on the `quotes` type instead of hooking into a bunch of methods (`Zero`, `Par`, etc...)
- I've been playing with a `Cashflow` type in ActuaryUtilities which would be very similar in concept to the current `ZeroCouponQuote` where the amount of interest is stored with the corresponding timepoint. So if `Cashflow` pans out (I'm having a hard time handling scalars, generators, and vectors), there would be a very similar feel between packages.

cc @kasperrisager

**Comment by kasperrisager** [comment]
This sounds like a really good idea to me, and I agree 100% with the benefits you list. It aligns well with conventional Julia wisdom that the specification of 'what' something is should be encoded in the type of an object and not in the function that works on it.

For Smith-Wilson, I suppose the usage would be something like
    
    `curve(SmithWilsonMethod(ufr, α), quotes)`

where `SmithWilsonMethod()` could be replaced by other construction method that also results in a SW curve (like one that fits α on the fly). Again, that is probably better than the current usage where the variation would have to be encoded in constructors.

**Comment by alecloudenback** [comment]
Working list of what the quotes would look like:

```
abstract type Observable end

abstract type ObservablePrice end
abstract type ObservableYield end
```
Where the `ObservablePrice` is when calibrating to an instruments quoted price and `ObservableYield`.

Concrete types:

## ZCBs

```julia
ZeroCouponBondPrice <: ObservablePrice
ZeroCouponBondYield <: ObservableYield
```

Just need maturity and price OR yield to maturity.

Questions:

- None

## Swaps

```julia
SwapPrice <: ObservablePrice
SwapYield <: ObservableYield
```

fields:
- `coupon_rate`
- `maturity`
- `frequency` where the default is 2(?)


## Bonds

`ParBondYield`

`BondYield` and `BondPrice` (i.e. a `BulletBond`, but no need for the longer name?)

with fields:

- `price` or `yield`
- `coupon_rate`
- `maturity`
- `frequency` (default of 2?)

`CMT`

Represents common treasury bonds (where there are no coupons for maturities < 1 year, and 2x per year after that. A convenience constructor for `BondYield`?

## Other

### Forward Rates

```
struct ForwardYield <: ObservableYield
	rate
	duration=1
end
```
Represents the forward rate applicable for a given duration. An ordered vector of rates implies a term structure.
