### ISSUE TITLE
New function: `forwardcurve`

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/Yields.jl#63]
`forwardcurve(YieldCurve,time)` would construct a new `YieldCuve` implied by the old one starting at `time`.

@kasperrisager any thoughts on the best way to accomplish this with `SmithWilson`? I think the others I can picture how this would be written but my inexperienced SW view is that it would be more difficult to do?

**Comment by kasperrisager** [comment]
The forward of a SW is not a SW, so I think there would have to be a fallback like `discount(f::FwdCurve, t) = discount(f.orig, t+f.u)/discount (f.orig, f.u)` that SW would fall into. I guess the same could be said about a curve that's interpolated linearly in `Rate`, couldn't it?
