### ISSUE TITLE
Cubic splines?

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/Yields.jl#99]
@kasperrisager I think I've realized that maybe I didn't intend to use cubic splines. I can't share the data here, but I noted that a quadratic spline is closest to what I saw come out of another system for curve fitting. *What should be standard in your opinion? True cubic seemed to be too extreme on the data I was looking at.

I haven't read it fully, but this paper seems very good at discussing the tradeoffs of different approaches in general: 
[HaganWest.pdf](https://github.com/JuliaActuary/Yields.jl/files/8683771/HaganWest.pdf). I mostly envisioned Yields for simple discounting and curve manipulation for modeling purposes, not complex hedging.

This PR, https://github.com/JuliaActuary/Yields.jl/pull/98,  commit changed it to quadratic spline, despite my mistake in calling it a cubic spline. Note that BSplineKit and Wikipedia terminology uses order 3 to mean quadratic, and order 4 to mean cubic.

I think the interpolation could remain as-is, but then I should update the docs/name to `QuadraticSpline` instead of `CubicSpline`

**Comment by kasperrisager** [comment]
Agree - it would be fine to just change the naming and leave it at the quadratic. I haven't stayed up to speed on what the best interpolation methods are (Hagan-West gives a good overview, but it seems a bit dated) but in actuarial practise, I've only seen up to linear, anyway. I guess if someone desperately needs cubic, it should be easy to do it based on the quadratic code.
